# Generated by Django 4.0.5 on 2022-07-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
    ]
