# Generated by Django 4.0.5 on 2022-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_profile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(default='Data have not been set yet'),
        ),
    ]
