# Generated by Django 4.0.5 on 2022-07-28 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('Finance', 'Finance'), ('Investing', 'Investing'), ('Sport', 'Sport'), ('Lifestyle', 'Lifestyle'), ('Technology', 'Technology'), ('Art', 'Art'), ('Health', 'Health'), ('Business', 'Business'), ('Literature', 'Literature'), ('History', 'History'), ('Culinaries', 'Culinaries')], max_length=50)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
